### ISSUE TITLE
Failed to configure bridge agent

### ISSUE THREAD

**Issue by josephsadek** [ibm-messaging/mft-cloud#15]
Iam try to create bridge agent on mft over openshift using cp4i 2022.2 and the following my configration
cat << EOF > mft-mqsc.mqsc
apiVersion: v1
kind: ConfigMap
metadata:
  name: mft-mqsc
data:
  agt.mqsc: |
    DEFINE CHANNEL(SABER.MFTCHL) CHLTYPE(SVRCONN) TRPTYPE(TCP)
    DEFINE CHANNEL(AGT.MFTCHL) CHLTYPE(SVRCONN) TRPTYPE(TCP)
    DEFINE CHANNEL(AGTQMSVRCONN) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')
    SET CHLAUTH(AGTQMSVRCONN) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)
    ALTER QMGR REPOS(MCLMFT)
    DEFINE CHANNEL(AGTQM.CRDQM) CHLTYPE(CLUSSDR) TRPTYPE(TCP) CONNAME('agtqm-ibm-mq (1414), crdqm-ibm-mq (1414)') CLUSTER(MCLMFT)
    START CHANNEL(AGTQM.CRDQM)
    DEFINE CHANNEL(CRDQM.AGTQM) CHLTYPE(CLUSRCVR) TRPTYPE(TCP) CONNAME('agtqm-ibm-mq (1414), crdqm-ibm-mq (1414)') CLUSTER(MCLMFT)
    START CHANNEL(CRDQM.AGTQM)
    ALTER QMGR CHLAUTH(DISABLED) CONNAUTH('')
  crd.mqsc: |
    DEFINE CHANNEL(CRDQMSVRCONN) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')
    SET CHLAUTH(CRDQMSVRCONN) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)
    DEFINE CHANNEL(MFTCORDSVRCONN) CHLTYPE(SVRCONN) TRPTYPE(TCP)
    ALTER QMGR REPOS(MCLMFT)
    DEFINE CHANNEL(AGTQM.CRDQM) CHLTYPE(CLUSRCVR) TRPTYPE(TCP) CONNAME('agtqm-ibm-mq (1414), crdqm-ibm-mq (1414)') CLUSTER(MCLMFT)
    START CHANNEL(AGTQM.CRDQM)
    DEFINE CHANNEL(CRDQM.AGTQM) CHLTYPE(CLUSSDR) TRPTYPE(TCP) CONNAME('crdqm-ibm-mq (1414), agtqm-ibm-mq (1414)') CLUSTER(MCLMFT)
    START CHANNEL(CRDQM.AGTQM)
    ALTER QMGR CHLAUTH(DISABLED) CONNAUTH('')
    DEFINE TOPIC('SYSTEM.FTE') TOPICSTR('SYSTEM.FTE') REPLACE
    ALTER TOPIC('SYSTEM.FTE') NPMSGDLV(ALLAVAIL) PMSGDLV(ALLAVAIL)
    DEFINE QLOCAL(SYSTEM.FTE) LIKE(SYSTEM.BROKER.DEFAULT.STREAM) REPLACE
    ALTER QLOCAL(SYSTEM.FTE) DESCR('Stream for MQMFT Pub/Sub interface')
    DISPLAY NAMELIST(SYSTEM.QPUBSUB.QUEUE.NAMELIST)
    ALTER NAMELIST(SYSTEM.QPUBSUB.QUEUE.NAMELIST) +
    NAMES(SYSTEM.BROKER.DEFAULT.STREAM+
    ,SYSTEM.BROKER.ADMIN.STREAM,SYSTEM.FTE)
    DISPLAY QMGR PSMODE
    ALTER QMGR PSMODE(ENABLED)
EOF

-----------------------
cat << EOF > saberpba01-mft.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: saberpba01-mft
  namespace: mft
data:
  saberpba01.mqsc: |
    DEFINE QLOCAL(SYSTEM.FTE.COMMAND.SABERPBA01) +
        DEFPRTY(0) +
        DEFSOPT(SHARED) +
        GET(ENABLED) +
        MAXDEPTH(5000) +
        MAXMSGL(4194304) +
        MSGDLVSQ(PRIORITY) +
        PUT(ENABLED) +
        RETINTVL(999999999) +
        SHARE +
        NOTRIGGER +
        USAGE(NORMAL) +
        REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.DATA.SABERPBA01) +
        DEFPRTY(0) +
        DEFSOPT(SHARED) +
        GET(ENABLED) +
        MAXDEPTH(5000) +
        MAXMSGL(4194304) +
        MSGDLVSQ(PRIORITY) +
        PUT(ENABLED) +
        RETINTVL(999999999) +
        SHARE +
        NOTRIGGER +
        USAGE(NORMAL) +
        REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.REPLY.SABERPBA01) +
        DEFPRTY(0) +
        DEFSOPT(SHARED) +
        GET(ENABLED) +
        MAXDEPTH(5000) +
        MAXMSGL(4194304) +
        MSGDLVSQ(PRIORITY) +
        PUT(ENABLED) +
        RETINTVL(999999999) +
        SHARE +
        NOTRIGGER +
        USAGE(NORMAL) +
        REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.STATE.SABERPBA01) +
        DEFPRTY(0) +
        DEFSOPT(SHARED) +
        GET(ENABLED) +
        MAXDEPTH(5000) +
        MAXMSGL(4194304) +
        MSGDLVSQ(PRIORITY) +
        PUT(ENABLED) +
        RETINTVL(999999999) +
        SHARE +
        NOTRIGGER +
        USAGE(NORMAL) +
        REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.EVENT.SABERPBA01) +
        DEFPRTY(0) +
        DEFSOPT(SHARED) +
        GET(ENABLED) +
        MAXDEPTH(5000) +
        MAXMSGL(4194304) +
        MSGDLVSQ(PRIORITY) +
        PUT(ENABLED) +
        RETINTVL(999999999) +
        SHARE +
        NOTRIGGER +
        USAGE(NORMAL) +
        REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHAGT1.SABERPBA01) +
        DEFPRTY(0) +
        DEFSOPT(SHARED) +
        GET(ENABLED) +
        MAXDEPTH(0) +
        MAXMSGL(0) +
        MSGDLVSQ(PRIORITY) +
        PUT(ENABLED) +
        RETINTVL(999999999) +
        SHARE +
        NOTRIGGER +
        USAGE(NORMAL) +
        REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHTRN1.SABERPBA01) +
        DEFPRTY(0) +
        DEFSOPT(SHARED) +
        GET(ENABLED) +
        MAXDEPTH(0) +
        MAXMSGL(0) +
        MSGDLVSQ(PRIORITY) +
        PUT(ENABLED) +
        RETINTVL(999999999) +
        SHARE +
        NOTRIGGER +
        USAGE(NORMAL) +
        REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHOPS1.SABERPBA01) +
        DEFPRTY(0) +
        DEFSOPT(SHARED) +
        GET(ENABLED) +
        MAXDEPTH(0) +
        MAXMSGL(0) +
        MSGDLVSQ(PRIORITY) +
        PUT(ENABLED) +
        RETINTVL(999999999) +
        SHARE +
        NOTRIGGER +
        USAGE(NORMAL) +
        REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHSCH1.SABERPBA01) +
        DEFPRTY(0) +
        DEFSOPT(SHARED) +
        GET(ENABLED) +
        MAXDEPTH(0) +
        MAXMSGL(0) +
        MSGDLVSQ(PRIORITY) +
        PUT(ENABLED) +
        RETINTVL(999999999) +
        SHARE +
        NOTRIGGER +
        USAGE(NORMAL) +
        REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHMON1.SABERPBA01) +
        DEFPRTY(0) +
        DEFSOPT(SHARED) +
        GET(ENABLED) +
        MAXDEPTH(0) +
        MAXMSGL(0) +
        MSGDLVSQ(PRIORITY) +
        PUT(ENABLED) +
        RETINTVL(999999999) +
        SHARE +
        NOTRIGGER +
        USAGE(NORMAL) +
        REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHADM1.SABERPBA01) +
        DEFPRTY(0) +
        DEFSOPT(SHARED) +
        GET(ENABLED) +
        MAXDEPTH(0) +
        MAXMSGL(0) +
        MSGDLVSQ(PRIORITY) +
        PUT(ENABLED) +
        RETINTVL(999999999) +
        SHARE +
        NOTRIGGER +
        USAGE(NORMAL) +
        REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.HA.SABERPBA01) +
        DEFPRTY(0) +
        DEFSOPT(SHARED) +
        GET(ENABLED) +
        MAXDEPTH(0) +
        MAXMSGL(0) +
        MSGDLVSQ(PRIORITY) +
        PUT(ENABLED) +
        RETINTVL(999999999) +
        SHARE +
        NOTRIGGER +
        USAGE(NORMAL) +
        REPLACE
EOF

----------------------
cat << EOF > configMapnew.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: mqmft-bridge-config
  namespace: mft

data:
  mqmftcfg.json: >
    {"waitTimeToStart":20,"coordinationQMgr":{"name":"CRDQM","host":"crdqm-ibm-mq","port":1414,"channel":"MFTCORDSVRCONN","additionalProperties":{}},"commandQMgr":{"name":"CRDQM","host":"crdqm-ibm-mq","port":1414,"channel":"MFTCORDSVRCONN","additionalProperties": {}},"agents":[{"name":"SABERPBA01","type":"BRIDGE",    "deleteOnTermination":"true","cleanOnStart":"all",    "qmgrName":"AGTQM","qmgrHost":"agtqm-ibm-mq","qmgrPort":1414,"qmgrChannel":"SABER.MFTCHL","protocolBridge":    {"serverType":"SFTP","serverHost":"saneussftptestinng02.blob.core.windows.net","serverPlatform":"UNIX","serverLocale":"en-GB","listFormat"="UNIX",    "limitedWrite"="false", "serverFileEncoding"="UTF8", "passiveMode"="true",    "protocolBridgeProperties" : {}},    "additionalProperties":{"logCapture":"true","enableQueueInputOutput":"false",    "protocolBridgeCredentialConfiguration":"/mqmftbridgecred/agentcreds/ProtocolBridgeCredentials.prop"}}]}
EOF
--------------------------------------
cat << EOF> CRDQM.yaml
apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: crdqm
spec:
  license:
    accept: true
    license: L-YBXJ-ADJNSM
    use: NonProduction
  queueManager:
    name: CRDQM
    mqsc:
    - configMap:
        name: mft-mqsc
        items:
        - crd.mqsc
    storage:
      queueManager:
        type: ephemeral
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: 9.3.3.3-r1
  web:
    enabled: true
  pki:
    keys:
      - name: sec
        secret:
          secretName: crd-tls-secret
          items:
          - tls.key
          - tls.crt
EOF

-----------------------------
cat << EOF> AGTQM.yaml
apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: agtqm
spec:
  license:
    accept: true
    license: L-YBXJ-ADJNSM
    use: NonProduction
  queueManager:
    name: AGTQM
    mqsc:
    - configMap:
        name: mft-mqsc
        items:
        - agt.mqsc
    - configMap:
        name: saberpba01-mft
        items:
        - saberpba01.mqsc
    storage:
      queueManager:
        type: ephemeral
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: 9.3.3.3-r1
  web:
    enabled: true
  pki:
    keys:
      - name: agt
        secret:
          secretName: agt-tls-secret
          items:
          - tls.key
          - tls.crt
EOF
----------------------------
cat << EOF > configMapnew.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: pba-custom-cred-map
  namespace: mft
data:
  ProtocolBridgeCredentials.prop: saneussftptestinng02.blob.core.windows.net=saneussftptestinng02.dev.devuser1!0!QGlVmoFO7FPs04WmtO6SViPc2wLoQo1C
EOF

----------------------------
cat << EOF > saberpba01mod.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ibm-mq-managed-file-transfer-saberpba01
  namespace: mft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibm-mq-managed-file-transfer-saberpba01
  template:
    metadata:
      labels:
        app: ibm-mq-managed-file-transfer-saberpba01
        deploymentconfig: ibm-mq-managed-file-transfer-saberpba01
    spec:
      volumes:
        - name: mqmft-bridge-config-map 
          configMap:
            name: mqmft-bridge-config 
        - name: mqmft-protocol-bridge-cred-map
          configMap:
            name: pba-custom-cred-map
      containers:
        - resources: {}
          readinessProbe:
            exec:
              command:
                - agentready
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /mnt/termination-log
          name: ibm-mq-managed-file-transfer-saberpba01
          livenessProbe:
            exec:
              command:
                - agentalive
            initialDelaySeconds: 90
            timeoutSeconds: 5
            periodSeconds: 90
            successThreshold: 1
            failureThreshold: 3	
          env:
            - name: MFT_AGENT_NAME
              value: SABERPBA01
            - name: LICENSE
              value: accept
            - name: MFT_AGENT_CONFIG_FILE 
              value: /mqmftcfg/agentconfig/mqmftcfg.json
            - name: MFT_BRIDGE_CREDENTIAL_FILE
              value: /mqmftbridgecred/agentcreds/ProtocolBridgeCredentials.prop
            - name: MFT_LOG_LEVEL
              value: "info"
            - name: MFT_TRACE_COMMAND
              value: "yes"
            - name: MFT_TRACE_COMMAND_PATH
              value: /mnt/mftdata
          imagePullPolicy: Always
          volumeMounts:
            - name: mqmft-bridge-config-map
              mountPath: /mqmftcfg/agentconfig
            - name: mqmft-protocol-bridge-cred-map
              mountPath: /mnt/credentials/  
          terminationMessagePolicy: File 
          image: >-
             acrneudaro01.azurecr.io/ibm-messaging/mqmft:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
EOF
--------------------------------------
But I get this error 
[13/03/2024 21:43:34.941 UTC] Diangostic log level set to 'info'.
[13/03/2024 21:43:34.941 UTC] CPU Architecture: amd64
[13/03/2024 21:43:34.941 UTC] Container Runtime: kube.
[13/03/2024 21:43:34.941 UTC] Base image: Red Hat Universal Base Image 
[13/03/2024 21:43:34.941 UTC] Running as user ID 1000780000 with primary group 0
[13/03/2024 21:43:34.941 UTC] Image created: 2023-11-01T02:07:09+00:00
[13/03/2024 21:43:34.941 UTC] IBM MQ Managed File Transfer Redistributable Agent: 9.3.4.0 Build Level: p934-L230927_P
[13/03/2024 21:43:34.944 UTC] Creating configuration for agent SABERPBA01.
[13/03/2024 21:43:34.944 UTC] Transfer root directory '/mountpath' created
[13/03/2024 21:43:34.944 UTC] Agent configuration and log directory: /mnt/mftdata.
[13/03/2024 21:43:34.944 UTC] Setting up coordination configuration for agent SABERPBA01. Name of the coordination queue manager CRDQM.
[13/03/2024 21:43:38.602 UTC] Coordination configuration for CRDQM is complete.
[13/03/2024 21:43:38.602 UTC] Setting up commands configuration for agent SABERPBA01. Name of the command queue manager: CRDQM.
[13/03/2024 21:43:42.150 UTC] Commands configuration for CRDQM is complete.
[13/03/2024 21:43:42.150 UTC] Creating BRIDGE type configuration for agent SABERPBA01.
[13/03/2024 21:43:42.150 UTC] Information required to setup bridge agent not found. Can not continue.
[13/03/2024 21:43:42.150 UTC] Failed to configure agent SABERPBA01. Container will end now. Review and fix any errors and then resubmit request.

**Comment by ShashikanthRaoT** [comment]
Hello @josephsadek Thank you for raising this issue. I shall investigate and update you at the earliest.

Regards

**Comment by josephsadek** [comment]
I figure some problem in my configuration and fixed it as following 
kind: ConfigMap
apiVersion: v1
metadata:
  name: mqmft-bridge-config
  namespace: mft
data:
  mqmftcfg.json: |
    {
    "waitTimeToStart":20,
    "coordinationQMgr":{
      "name":"CRDQM",
      "host":"crdqm-ibm-mq",
      "port":1414,
      "channel":"MFTCORDSVRCONN",
      "qmgrCredentials" : {
        "mqUserId":"mquser",
        "mqPassword":"cGFzc3cwcmQ="},
      "additionalProperties":{}
    },
    "commandQMgr":{
      "name":"CRDQM",
      "host":"crdqm-ibm-mq",
      "port":1414,
      "channel":"MFTCORDSVRCONN",
      "qmgrCredentials" : {
        "mqUserId":"mquser",
        "mqPassword":"cGFzc3cwcmQ="},
      "additionalProperties": {}
    },
    "agents":[
      {
        "name":"SABERPBA01",
        "type":"BRIDGE", 
        "deleteOnTermination":"true",
        "cleanOnStart":"all",
        "qmgrName":"AGTQM",
        "qmgrHost":"agtqm-ibm-mq",
        "qmgrPort":1414,
        "qmgrChannel":"SABER.MFTCHL",
        "qmgrCredentials" : {
          "mqUserId":"mquser",
          "mqPassword":"cGFzc3cwcmQ="},
        "defaultServer" :"mySFTPserver",
        "maxActiveDestinationTransfers":25,
        "failTransferWhenCapacityReached":"true",
        "additionalProperties":{
          "logCapture":"true",
          "enableQueueInputOutput":"false", 
          "protocolBridgeCredentialConfiguration":"/mnt/credentials/ProtocolBridgeCredentials.prop"
        },
        "protocolServers": [{
          "name":"mySFTPserver",
          "type":"SFTP",
          "host":"saneussftptestinng02.blob.core.windows.net",
          "platform":"windows",
          "locale":"en_GB",
          "fileEncoding":"UTF-8",
          "limitedWrite":"false",
          "connectionTimeout":60
              }]
          }]
          }

and create Deployment again as following 
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ibm-mq-managed-file-transfer-saberpba01
  namespace: mft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibm-mq-managed-file-transfer-saberpba01
  template:
    metadata:
      labels:
        app: ibm-mq-managed-file-transfer-saberpba01
        deploymentconfig: ibm-mq-managed-file-transfer-saberpba01
    spec:
      volumes:
        - name: mqmft-bridge-config-map 
          configMap:
            name: mqmft-bridge-config 
        - name: mqmft-protocol-bridge-cred-map
          configMap:
            name: pba-custom-cred-map
        - name: mqmft-saberpba01-config 
          persistentVolumeClaim:
            claimName: saberpba01-pvc
      containers:
        - resources: {}
          readinessProbe:
            exec:
              command:
                - agentready
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /mnt/termination-log
          name: ibm-mq-managed-file-transfer-saberpba01
          livenessProbe:
            exec:
              command:
                - agentalive
            initialDelaySeconds: 90
            timeoutSeconds: 5
            periodSeconds: 90
            successThreshold: 1
            failureThreshold: 3	
          env:
            - name: MFT_AGENT_NAME
              value: SABERPBA01
            - name: LICENSE
              value: accept
            - name: BFG_DATA 
              value: /mnt/mftdata
            - name: MFT_AGENT_CONFIG_FILE 
              value: /mqmftcfg/agentconfig/mqmftcfg.json
            - name: MFT_BRIDGE_CREDENTIAL_FILE
              value: /mnt/credentials/ProtocolBridgeCredentials.prop
            - name: MFT_LOG_LEVEL
              value: "info"
            - name: MFT_TRACE_COMMAND
              value: "yes"
            - name: MFT_TRACE_COMMAND_PATH
              value: /mnt/mftdata 
          imagePullPolicy: Always
          volumeMounts:
            - name: mqmft-bridge-config-map
              mountPath: /mqmftcfg/agentconfig
            - name: mqmft-protocol-bridge-cred-map
              mountPath: /mnt/credentials  
            - name: mqmft-saberpba01-config
              mountPath: /mnt/mftdata
              subPath: mftdata
          terminationMessagePolicy: File 
          image: >-
             acrneudaro01.azurecr.io/ibm-messaging/mqmft:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler

and I can see agent configure but facing new error as following 

[14/03/2024 20:47:52:231 GMT] 00000001 Agent         I   BFGAG0204I: Agent is running in 'oci' container runtime.
[14/03/2024 20:47:52:372 GMT] 00000001 RASImpl       I   BFGUT0039I: The transfer log specification has changed to "info".
[14/03/2024 20:47:52:453 GMT] 00000001 UserExitsFact E   BFGUE0034E: The agent cannot continue because the user exit class 'com.ibm.wmq.bridgecredentialexit.ProtocolBridgeCustomCredentialExit' referenced by property 'protocolBridgeCredentialExitClasses' because this class threw an exception during its instantiation.  The exception is: java.lang.NoClassDefFoundError: org.json.JSONException
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Caused by: java.lang.ClassNotFoundException: org.json.JSONException
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal
Failed to process log message - invalid character '\t' in string literal

[14/03/2024 20:47:52:686 GMT] 00000001 ABENDImpl     E   BFGUT0003E: An internal error has occurred. An unexpected condition has occurred that has resulted in the abnormal end of this process.  Failure data was captured in file "ABEND.FTE.20240314204752455.9078085139541639507.log".
[14/03/2024 20:48:05.672 UTC] Command output: 5724-H72 Copyright IBM Corp.  2008, 2023.  ALL RIGHTS RESERVED
Couldn't create user preferences directory. User preferences are unusable.
java.io.IOException: No such file or directory
BFGCL0212I: Issuing ping request to agent SABERPBA01
BFGCL0214I: Agent SABERPBA01 didn't respond to ping after 10 seconds.

Error: .
[14/03/2024 20:48:05.672 UTC] Agent SABERPBA01 has not started yet. Status will be verified again after 10 seconds.
[14/03/2024 20:48:15.672 UTC] Verifying status of agent SABERPBA01.
[14/03/2024 20:48:29.097 UTC] Command output: 5724-H72 Copyright IBM Corp.  2008, 2023.  ALL RIGHTS RESERVED
Couldn't create user preferences directory. User preferences are unusable.
java.io.IOException: No such file or directory
BFGCL0212I: Issuing ping request to agent SABERPBA01
BFGCL0214I: Agent SABERPBA01 didn't respond to ping after 10 seconds.

Error: .
[14/03/2024 20:48:29.097 UTC] Agent SABERPBA01 did not start.
[ibm-mq-managed-file-transfer-saberpba01-b766bcdd-krw9b-ibm-mq-managed-file-transfer-saberpba01 (4).log](https://github.com/ibm-messaging/mq-container-mft/files/14608460/ibm-mq-managed-file-transfer-saberpba01-b766bcdd-krw9b-ibm-mq-managed-file-transfer-saberpba01.4.log)

you can see full log from attach

**Comment by ShashikanthRaoT** [comment]
Thanks for update.

An update has been made to the developer version of the MFT container image that fixes the reported issue. Please try again with the latest image from icr.io/ibm-messaging/mqmft:latest.

**Comment by josephsadek** [comment]
thanks shahikanth for your support
