### ISSUE TITLE
Slash added to Windows Path 

### ISSUE THREAD

**Issue by nickwe3** [ibm-messaging/mft-cloud#21]
Hello,

When using the latest cloud version 9.4.1 on an openshift pod, transfers to Windows MQFT agent failed because the HBA agent add / at the end of destination directory, like this:

```
      <destination type="file">
        <file size="-1">D:\mqft\mqftftphbaqa01\wonderautof02\output\new/</file>
      </destination>
```

or 

```
      <destination type="file">
        <file size="-1">D:\mqft\mqftftphbaqa01\wonderautof02\output\new\/</file>
      </destination>
```

Would there be a way to avoid this slash to be added, or to be replace by a back slash in case of Windows Path ?

Thanks and Regards,

Nicolas.

**Comment by ShashikanthRaoT** [comment]
Hi, Thankyou for raising this query.  Was the behavior different in earlier version image? As far as I know not much changed in 9.4.1 release. I shall try to recreate and post my findings.

**Comment by nickwe3** [comment]
Hello,

Thanks for the follow up.

We had other problem with 9.4.0 (cipher) so we never got to that point. 

And we couldn't test earlier because we needed the support usage of SSH Private Keys.

But we've discovered another problem for which we'll open a PMR at IBM this morning, it's that the -dd argument (destination directory) is expecting a path with a filename exactly like -df (destination file), if we just define a directory, it failed. The exact same fteCreateTransfer with -dd is working fine on HBA 9.3 agent on Windows VM.

We'll let you know about our findings.

Thanks.

**Comment by ShashikanthRaoT** [comment]
Hello,

Thanks for the update. But please note that PMR can't be raised for issues found in MFT Container Image as is it is a "Developer" only version. You can raise a Git Issue though. If the issue is recreatable with the MFT on-prem version, then you can raise a PMR.

**Comment by nickwe3** [comment]
Follow up in issue 22:

- https://github.com/ibm-messaging/mq-container-mft/issues/22
