### ISSUE TITLE
Is the doNotUseTempOutputFile supported?

### ISSUE THREAD

**Issue by goffinet** [ibm-messaging/mft-cloud#23]
Hello @ShashikanthRaoT,
cc: @nickwe3

Is the doNotUseTempOutputFile supported in agent.properties files (https://www.ibm.com/docs/en/ibm-mq/9.4?topic=reference-mft-agentproperties-file)?

Best regards,

**Comment by ShashikanthRaoT** [comment]
Yes, it is supported.

**Comment by goffinet** [comment]
Thank you.
